#!/usr/bin/env bash
#SBATCH --account=rwth2182
#SBATCH --partition=c23g
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=16
#SBATCH --mem=96G
#SBATCH --time=03:00:00
#SBATCH --array=1-8
#SBATCH --job-name=leapef-wml
#SBATCH --output=slurm/logs/leapef_wml_%A_%a.out
export EF_ARM=WML_ent
bash "$HOME/repos/reppo/slurm/leap_ef_launch.sh"
